### ISSUE TITLE
Add point about the usefulness of dynamic path properties

### ISSUE THREAD

**Issue by theri** [panrg/path-properties#72]
Via @SpencerDawkins in Last Call:

> I’m not sure where to put it, but some of the dynamic path properties can be so dynamic that they aren’t useful in path-aware networking. For example, link usage for bursty traffic may vary so dramatically that this property can’t be used to select between paths without applying dampening or otherwise avoiding oscillation. This is somewhat related to https://www.rfc-editor.org/rfc/rfc9049.html#name-reacting-to-distant-signals, and has been mentioned about every two years for the entire time ALTO has been chartered. 🙂
>
> Perhaps following this paragraph? 
>
> Some path properties express the performance of the transmission of a packet or flow over a link or subpath. Such transmission performance properties can be measured or approximated, e.g., by endpoints or by path elements on the path, or they may be available as cost metrics, see [I-D.ietf-alto-performance-metrics]. Transmission performance properties may be made available in an aggregated form, such as averages or minimums. Properties related to a path element which constitutes a single layer 2 domain are abstracted from the used physical and link layer technology, similar to [RFC8175].

**Comment by cyrill-k** [comment]
I agree with you that a clear classification of properties is difficult.
Maybe we can add some text to discuss that some properties are more dynamic or more distant than others?

**Comment by theri** [comment]
Yes. I can take a first stab at this text.

**Comment by cyrill-k** [comment]
I like the text and I think it clearly illustrates the problem.
However, we now have this discussion of potential problems caused by dynamic observed properties (and path selection based on such properties) in four places (here [middle of 4], first paragraph of 3.1, second paragraph of 3.1, and second paragraph of 4).

Should we consider merging some of them?
Maybe we could merge this text and the previous one (second paragraph of 4) and the two occurrences in section 3.1.

What do you think?
